/**
 * Rocket.Chat HTTP Client
 *
 * Lightweight wrapper around fetch for making authenticated API calls
 * to a Rocket.Chat server instance.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 */

export class RCClient {
  private baseUrl: string;
  private authToken: string | null = null;
  private userId: string | null = null;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
  }

  /** Set authentication credentials (called after login) */
  setAuth(authToken: string, userId: string): void {
    this.authToken = authToken;
    this.userId = userId;
  }

  /** Check if the client is authenticated */
  isAuthenticated(): boolean {
    return this.authToken !== null && this.userId !== null;
  }

  /** Make a GET request */
  async get(path: string): Promise<unknown> {
    return this.request("GET", path);
  }

  /** Make a POST request */
  async post(path: string, body?: unknown): Promise<unknown> {
    return this.request("POST", path, body);
  }

  /** Make a PUT request */
  async put(path: string, body?: unknown): Promise<unknown> {
    return this.request("PUT", path, body);
  }

  /** Make a DELETE request */
  async delete(path: string, body?: unknown): Promise<unknown> {
    return this.request("DELETE", path, body);
  }

  /** Make a PATCH request */
  async patch(path: string, body?: unknown): Promise<unknown> {
    return this.request("PATCH", path, body);
  }

  private async request(method: string, path: string, body?: unknown): Promise<unknown> {
    const url = `${this.baseUrl}${path}`;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };

    if (this.authToken && this.userId) {
      headers["X-Auth-Token"] = this.authToken;
      headers["X-User-Id"] = this.userId;
    }

    const response = await fetch(url, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(
        `RC API Error [${response.status}] ${method} ${path}: ${errorBody}`
      );
    }

    return response.json();
  }
}
