/**
 * Tests for MCP Tool: archive_channel
 *
 * Auto-generated by rc-mcp.
 * Validates Zod schema and handler function for this tool.
 */

import { describe, it, expect } from "vitest";
import { z } from "zod";
import { archive_channelSchema, register_archive_channel } from "../src/tools/archive_channel.js";

describe("archive_channel Zod Schema", () => {
  it("should have a valid Zod object schema", () => {
    expect(archive_channelSchema).toBeDefined();
    expect(archive_channelSchema instanceof z.ZodObject).toBe(true);
  });

  it("should enforce required fields (if any)", () => {
    // We dynamically check required fields from the parsed schema shape
    const shape = archive_channelSchema.shape;
    const requiredKeys = Object.keys(shape).filter((key) => {
      const field = shape[key as keyof typeof shape];
      // A field is required if it's NOT explicitly optional
      return !(field instanceof z.ZodOptional);
    });

    if (requiredKeys.length === 0) {
      // If no required fields, an empty object should pass
      const result = archive_channelSchema.safeParse({});
      expect(result.success).toBe(true);
    } else {
      // If there are required fields, an empty object should fail
      const result = archive_channelSchema.safeParse({});
      expect(result.success).toBe(false);

      if (!result.success) {
        // Verify that the error mentions the missing required fields
        const errorPaths = result.error.errors.map((e) => e.path[0]);
        for (const reqKey of requiredKeys) {
          expect(errorPaths).toContain(reqKey);
        }
      }
    }
  });

  it("should reject invalid data types", () => {
    // Passing a complete mismatch should fail
    const resultString = archive_channelSchema.safeParse("not-an-object");
    expect(resultString.success).toBe(false);

    const resultNumber = archive_channelSchema.safeParse(42);
    expect(resultNumber.success).toBe(false);

    const resultArray = archive_channelSchema.safeParse([]);
    expect(resultArray.success).toBe(false);
  });

  it("should export a register function for MCP server integration", () => {
    expect(register_archive_channel).toBeDefined();
    expect(typeof register_archive_channel).toBe("function");
  });
});
