/**
 * Tests for MCP Tool: channels_info
 *
 * Auto-generated by rc-mcp.
 * Validates Zod schema and handler function for this tool.
 */

import { describe, it, expect } from "vitest";
import { z } from "zod";
import { channels_infoSchema, register_channels_info } from "../src/tools/channels_info.js";

describe("channels_info Zod Schema", () => {
  it("should have a valid Zod object schema", () => {
    expect(channels_infoSchema).toBeDefined();
    expect(channels_infoSchema instanceof z.ZodObject).toBe(true);
  });

  it("should enforce required fields (if any)", () => {
    // We dynamically check required fields from the parsed schema shape
    const shape = channels_infoSchema.shape;
    const requiredKeys = Object.keys(shape).filter((key) => {
      const field = shape[key as keyof typeof shape];
      // A field is required if it's NOT explicitly optional
      return !(field instanceof z.ZodOptional);
    });

    if (requiredKeys.length === 0) {
      // If no required fields, an empty object should pass
      const result = channels_infoSchema.safeParse({});
      expect(result.success).toBe(true);
    } else {
      // If there are required fields, an empty object should fail
      const result = channels_infoSchema.safeParse({});
      expect(result.success).toBe(false);

      if (!result.success) {
        // Verify that the error mentions the missing required fields
        const errorPaths = result.error.errors.map((e) => e.path[0]);
        for (const reqKey of requiredKeys) {
          expect(errorPaths).toContain(reqKey);
        }
      }
    }
  });

  it("should reject invalid data types", () => {
    // Passing a complete mismatch should fail
    const resultString = channels_infoSchema.safeParse("not-an-object");
    expect(resultString.success).toBe(false);

    const resultNumber = channels_infoSchema.safeParse(42);
    expect(resultNumber.success).toBe(false);

    const resultArray = channels_infoSchema.safeParse([]);
    expect(resultArray.success).toBe(false);
  });

  it("should export a register function for MCP server integration", () => {
    expect(register_channels_info).toBeDefined();
    expect(typeof register_channels_info).toBe("function");
  });
});
