/**
 * Tests for MCP Tool: export_channel_history
 *
 * Auto-generated by rc-mcp.
 * Validates Zod schema and handler function for this tool.
 */

import { describe, it, expect } from "vitest";
import { z } from "zod";
import { export_channel_historySchema, register_export_channel_history } from "../src/tools/export_channel_history.js";

describe("export_channel_history Zod Schema", () => {
  it("should have a valid Zod object schema", () => {
    expect(export_channel_historySchema).toBeDefined();
    expect(export_channel_historySchema instanceof z.ZodObject).toBe(true);
  });

  it("should enforce required fields (if any)", () => {
    // We dynamically check required fields from the parsed schema shape
    const shape = export_channel_historySchema.shape;
    const requiredKeys = Object.keys(shape).filter((key) => {
      const field = shape[key as keyof typeof shape];
      // A field is required if it's NOT explicitly optional
      return !(field instanceof z.ZodOptional);
    });

    if (requiredKeys.length === 0) {
      // If no required fields, an empty object should pass
      const result = export_channel_historySchema.safeParse({});
      expect(result.success).toBe(true);
    } else {
      // If there are required fields, an empty object should fail
      const result = export_channel_historySchema.safeParse({});
      expect(result.success).toBe(false);

      if (!result.success) {
        // Verify that the error mentions the missing required fields
        const errorPaths = result.error.errors.map((e) => e.path[0]);
        for (const reqKey of requiredKeys) {
          expect(errorPaths).toContain(reqKey);
        }
      }
    }
  });

  it("should reject invalid data types", () => {
    // Passing a complete mismatch should fail
    const resultString = export_channel_historySchema.safeParse("not-an-object");
    expect(resultString.success).toBe(false);

    const resultNumber = export_channel_historySchema.safeParse(42);
    expect(resultNumber.success).toBe(false);

    const resultArray = export_channel_historySchema.safeParse([]);
    expect(resultArray.success).toBe(false);
  });

  it("should export a register function for MCP server integration", () => {
    expect(register_export_channel_history).toBeDefined();
    expect(typeof register_export_channel_history).toBe("function");
  });
});
