/**
 * Tests for MCP Tool: groups_archive
 *
 * Auto-generated by rc-mcp.
 * Validates Zod schema and handler function for this tool.
 */

import { describe, it, expect } from "vitest";
import { z } from "zod";
import { groups_archiveSchema, register_groups_archive } from "../src/tools/groups_archive.js";

describe("groups_archive Zod Schema", () => {
  it("should have a valid Zod object schema", () => {
    expect(groups_archiveSchema).toBeDefined();
    expect(groups_archiveSchema instanceof z.ZodObject).toBe(true);
  });

  it("should enforce required fields (if any)", () => {
    // We dynamically check required fields from the parsed schema shape
    const shape = groups_archiveSchema.shape;
    const requiredKeys = Object.keys(shape).filter((key) => {
      const field = shape[key as keyof typeof shape];
      // A field is required if it's NOT explicitly optional
      return !(field instanceof z.ZodOptional);
    });

    if (requiredKeys.length === 0) {
      // If no required fields, an empty object should pass
      const result = groups_archiveSchema.safeParse({});
      expect(result.success).toBe(true);
    } else {
      // If there are required fields, an empty object should fail
      const result = groups_archiveSchema.safeParse({});
      expect(result.success).toBe(false);

      if (!result.success) {
        // Verify that the error mentions the missing required fields
        const errorPaths = result.error.errors.map((e) => e.path[0]);
        for (const reqKey of requiredKeys) {
          expect(errorPaths).toContain(reqKey);
        }
      }
    }
  });

  it("should reject invalid data types", () => {
    // Passing a complete mismatch should fail
    const resultString = groups_archiveSchema.safeParse("not-an-object");
    expect(resultString.success).toBe(false);

    const resultNumber = groups_archiveSchema.safeParse(42);
    expect(resultNumber.success).toBe(false);

    const resultArray = groups_archiveSchema.safeParse([]);
    expect(resultArray.success).toBe(false);
  });

  it("should export a register function for MCP server integration", () => {
    expect(register_groups_archive).toBeDefined();
    expect(typeof register_groups_archive).toBe("function");
  });
});
