/**
 * Tests for MCP Tool: settings__id
 *
 * Auto-generated by rc-mcp.
 * Provides thorough validation of the generated Zod schema.
 */

import { describe, it, expect } from "vitest";
import { z } from "zod";
import { settings__idSchema } from "../src/tools/settings__id.js";

describe("settings__id Zod Schema", () => {
  it("should have a valid Zod object schema", () => {
    expect(settings__idSchema).toBeDefined();
    expect(settings__idSchema instanceof z.ZodObject).toBe(true);
  });

  it("should enforce required fields (if any)", () => {
    // We dynamically check required fields from the parsed schema shape
    const shape = settings__idSchema.shape;
    const requiredKeys = Object.keys(shape).filter((key) => {
      const field = shape[key as keyof typeof shape];
      // A field is required if it's NOT explicitly optional
      return !(field instanceof z.ZodOptional);
    });

    if (requiredKeys.length === 0) {
      // If no required fields, an empty object should pass
      const result = settings__idSchema.safeParse({});
      expect(result.success).toBe(true);
    } else {
      // If there are required fields, an empty object should fail
      const result = settings__idSchema.safeParse({});
      expect(result.success).toBe(false);

      if (!result.success) {
        // Verify that the error mentions the missing required fields
        const errorPaths = result.error.errors.map((e) => e.path[0]);
        for (const reqKey of requiredKeys) {
          expect(errorPaths).toContain(reqKey);
        }
      }
    }
  });

  it("should reject invalid data types", () => {
    // Passing a complete mismatch should fail
    const resultString = settings__idSchema.safeParse("not-an-object");
    expect(resultString.success).toBe(false);

    const resultNumber = settings__idSchema.safeParse(42);
    expect(resultNumber.success).toBe(false);

    const resultArray = settings__idSchema.safeParse([]);
    expect(resultArray.success).toBe(false);
  });
});
