/**
 * MCP Tool: groups_invite
 * Invite Users to Group. POST groups.invite API wrapper. Requires: roomId, userId.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/groups.invite
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const groups_inviteSchema = z.object({
    roomId: z.string().describe("The group ID. You can find the IDs by using any of the following endpoints: * <a href='https://developer.rocket.chat/apidocs/get-list-of-user-groups' target='_blank'>Get List of User Groups</a>: This endpoint returns all private channels in the workspace, if you have the required permissions to view them. * <a href='https://developer.rocket.chat/apidocs/get-groups' target='_blank'>Get Groups</a>: This endpoint returns the private channels that you are a member of."),
    userId: z.string().describe("The ID of the user to be invited. You can also use the parameter `userIds` as an array to invite more than one user. For example, `[\"nSYqWzZ4GsKTX4dyK\", \"SYqWzZ4Gsasdfgh\"]`")
  });

export function register_groups_invite(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "groups_invite",
    "Invite Users to Group. POST groups.invite API wrapper. Requires: roomId, userId.",
    groups_inviteSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed
        const apiPath = "/api/v1/groups.invite";
        const body = {
          roomId: params.roomId,
          userId: params.userId
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        let message = error instanceof Error ? error.message : String(error);
        if (message.includes("RC API Error")) {
          const match = message.match(/RC API Error \[(\d+)\] .*?: (.*)/);
          if (match) {
            message = `HTTP ${match[1]}: ${match[2]}`;
          }
        }
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
