/**
 * MCP Tool: login
 * Login with Username and Password
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/login
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const loginSchema = z.object({
    user: z.string().optional().describe("Your user name or email."),
    password: z.string().optional().describe("Your pasword."),
    resume: z.string().optional().describe("Your previously issued `authToken`."),
    code: z.string().optional().describe("The 2FA code. It is required if your account has two-factor authentication enabled .")
  });

export function register_login(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "login",
    "Login with Username and Password",
    loginSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed
        const apiPath = "/api/v1/login";
        const body = {
          user: params.user,
          password: params.password,
          resume: params.resume,
          code: params.code
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        let message = error instanceof Error ? error.message : String(error);
        if (message.includes("RC API Error")) {
          const match = message.match(/RC API Error \[(\d+)\] .*?: (.*)/);
          if (match) {
            message = `HTTP ${match[1]}: ${match[2]}`;
          }
        }
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
