/**
 * MCP Tool: onboard_user
 * Look up a user by username, resolve a room by name, invite them to the room, and send a welcome message. Spans user-management + rooms + ...
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/users.info
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const onboard_userSchema = z.object({
    username: z.string().describe("Username of the user to onboard"),
    roomName: z.string().describe("Name of the room to invite the user to"),
    welcomeText: z.string().describe("Welcome message to post in the room")
  });

export function register_onboard_user(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "onboard_user",
    "Look up a user by username, resolve a room by name, invite them to the room, and send a welcome message. Spans user-management + rooms + ...",
    onboard_userSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed

        // Store results from each step for parameter wiring
        const stepResults: unknown[] = [];

        // ── Step 1: Look up user by username ──
        const step0Params: Record<string, unknown> = {};
        if (params.username !== undefined) step0Params["username"] = params.username;
        let step0Result;
        {
          const step0Query = Object.entries(step0Params).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join("&");
          const step0Path = step0Query ? `/api/v1/users.info?${step0Query}` : "/api/v1/users.info";
          step0Result = await rcClient.get(step0Path);
        }
        stepResults.push(step0Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 2: Resolve the target room by name ──
        const step1Params: Record<string, unknown> = {};
        if (params.roomName !== undefined) step1Params["roomName"] = params.roomName;
        let step1Result;
        {
          const step1Query = Object.entries(step1Params).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join("&");
          const step1Path = step1Query ? `/api/v1/rooms.info?${step1Query}` : "/api/v1/rooms.info";
          step1Result = await rcClient.get(step1Path);
        }
        stepResults.push(step1Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 3: Invite user to the resolved room ──
        const step2Params: Record<string, unknown> = {};
        step2Params["userId"] = (stepResults[0] as any)?.user?._id;
        step2Params["roomId"] = (stepResults[1] as any)?.room?._id;
        let step2Result;
        try {
          step2Result = await rcClient.post("/api/v1/channels.invite", step2Params);
        } catch (err) {
          // Fallback to post-api-v1-groups.invite
          step2Result = await rcClient.post("/api/v1/groups.invite", step2Params);
        }
        stepResults.push(step2Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 4: Send welcome message to the room ──
        const step3Params: Record<string, unknown> = {};
        if (params.welcomeText !== undefined) step3Params["text"] = params.welcomeText;
        step3Params["roomId"] = (stepResults[1] as any)?.room?._id;
        let step3Result;
        step3Result = await rcClient.post("/api/v1/chat.postMessage", step3Params);
        stepResults.push(step3Result);

        // Return the final result from step 4
        return { content: [{ type: "text" as const, text: JSON.stringify(step3Result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Workflow "${"onboard_user"}" failed: ${message}` }], isError: true };
      }
    }
  );
}
