/**
 * MCP Tool: send_dm_to_user
 * Open a direct message conversation with a user and send them a message.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/dm.create
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const send_dm_to_userSchema = z.object({
    username: z.string().describe("Username to send DM to"),
    text: z.string().describe("Message text")
  });

export function register_send_dm_to_user(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "send_dm_to_user",
    "Open a direct message conversation with a user and send them a message.",
    send_dm_to_userSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed

        // Store results from each step for parameter wiring
        const stepResults: unknown[] = [];

        // ── Step 1: Create/open a DM with the target user ──
        const step0Params: Record<string, unknown> = {};
        if (params.username !== undefined) step0Params["username"] = params.username;
        let step0Result;
        step0Result = await rcClient.post("/api/v1/dm.create", step0Params);
        stepResults.push(step0Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 2: Send message in the DM ──
        const step1Params: Record<string, unknown> = {};
        if (params.text !== undefined) step1Params["text"] = params.text;
        step1Params["roomId"] = (stepResults[0] as any)?.room?._id;
        let step1Result;
        step1Result = await rcClient.post("/api/v1/chat.postMessage", step1Params);
        stepResults.push(step1Result);

        // Return the final result from step 2
        return { content: [{ type: "text" as const, text: JSON.stringify(step1Result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Workflow "${"send_dm_to_user"}" failed: ${message}` }], isError: true };
      }
    }
  );
}
