/**
 * MCP Tool: cannedresponses_get
 * Get User Canned Responses
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/canned-responses.get
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const cannedresponses_getSchema = z.object({});

export function register_cannedresponses_get(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "cannedresponses_get",
    "Get User Canned Responses",
    cannedresponses_getSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/canned-responses.get";
        const result = await rcClient.get(apiPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
