/**
 * MCP Tool: livechat_agent_info_rid_token
 * Get Agent Information
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/livechat/agent.info/{rid}/{token}
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const livechat_agent_info_rid_tokenSchema = z.object({
    rid: z.string().describe("The room ID."),
    token: z.string().describe("The visitor token.")
  });

export function register_livechat_agent_info_rid_token(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "livechat_agent_info_rid_token",
    "Get Agent Information",
    livechat_agent_info_rid_tokenSchema.shape,
    async (params) => {
      try {
        const apiPath = `/api/v1/livechat/agent.info/${params.rid}/${params.token}`;
        const result = await rcClient.get(apiPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
