/**
 * MCP Tool: livechat_visitor
 * Register Livechat Visitor
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/livechat/visitor
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const livechat_visitorSchema = z.object({
    visitor: z.object({
      name: z.string().optional().describe("The visitor's name."),
      email: z.string().optional().describe("The visitor's email."),
      department: z.string().optional().describe("The department that the visitor wants to register to."),
      token: z.string().describe("Enter a random unique string as the visitor token."),
      phone: z.string().optional().describe("The visitor's phone number."),
      username: z.string().optional().describe("The agent's username."),
      customFields: z.array(z.object({
      key: z.string().optional(),
      value: z.string().optional(),
      overwrite: z.boolean().optional()
    })).optional().describe("Enter the custom field key, value, and whether you want to overwrite this information.")
    }).describe("Enter the body parameters in the `visitor` object.")
  });

export function register_livechat_visitor(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "livechat_visitor",
    "Register Livechat Visitor",
    livechat_visitorSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/livechat/visitor";
        const body = {
          visitor: params.visitor
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
