/**
 * MCP Tool: livechat_department_autocomplete
 * Autocomplete Department
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/livechat/department.autocomplete
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const livechat_department_autocompleteSchema = z.object({
    selector: z.string().describe("Enter the exceptions or the conditions that you want to search for."),
    onlyMyDepartments: z.boolean().optional().describe("Only displays the departments that you are assigned to. The value can be boolean `true` or `false`"),
    showArchived: z.boolean().optional().describe("The result includes archived departments. The value can be Boolean `true` or `false`.")
  });

export function register_livechat_department_autocomplete(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "livechat_department_autocomplete",
    "Autocomplete Department",
    livechat_department_autocompleteSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/livechat/department.autocomplete";
        const queryParts: string[] = [];
        if (params.selector !== undefined) queryParts.push(`selector=${encodeURIComponent(String(params.selector))}`);
        if (params.onlyMyDepartments !== undefined) queryParts.push(`onlyMyDepartments=${encodeURIComponent(String(params.onlyMyDepartments))}`);
        if (params.showArchived !== undefined) queryParts.push(`showArchived=${encodeURIComponent(String(params.showArchived))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
