/**
 * MCP Tool: livechat_visitor_department_transfer
 * Visitor Transfer Room
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/livechat/visitor/department.transfer
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const livechat_visitor_department_transferSchema = z.object({
    token: z.string().describe("Enter the visitor token."),
    rid: z.string().describe("Enter the room ID."),
    department: z.string().describe("Enter the department ID to which you want to transfer the chat.")
  });

export function register_livechat_visitor_department_transfer(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "livechat_visitor_department_transfer",
    "Visitor Transfer Room",
    livechat_visitor_department_transferSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/livechat/visitor/department.transfer";
        const body = {
          token: params.token,
          rid: params.rid,
          department: params.department
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
