/**
 * MCP Tool: livechat_room_forward
 * Forward Omnichannel Room
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/livechat/room.forward
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const livechat_room_forwardSchema = z.object({
    roomId: z.string().describe("The room ID."),
    userId: z.string().optional().describe("The new agent ID."),
    departmentId: z.string().optional().describe("The new department ID.")
  });

export function register_livechat_room_forward(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "livechat_room_forward",
    "Forward Omnichannel Room",
    livechat_room_forwardSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/livechat/room.forward";
        const body = {
          roomId: params.roomId,
          userId: params.userId,
          departmentId: params.departmentId
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
