#!/usr/bin/env node
/**
 * rc-mcp-manage-channels — Minimal MCP Server
 * Minimal MCP server for Rocket.Chat: manage-channels
 *
 * Auto-generated by rc-mcp — do not edit manually.
 */

import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { RCClient } from "./rc-client.js";
import { authenticate } from "./auth.js";
import { register_login } from "./tools/login.js";
import { register_channels_create } from "./tools/channels_create.js";
import { register_channels_archive } from "./tools/channels_archive.js";
import { register_channels_unarchive } from "./tools/channels_unarchive.js";
import { register_channels_rename } from "./tools/channels_rename.js";
import { register_channels_setDescription } from "./tools/channels_setDescription.js";
import { register_channels_info } from "./tools/channels_info.js";
import { register_channels_list } from "./tools/channels_list.js";

async function main() {
  // Initialize the MCP server
  const server = new McpServer({
    name: "rc-mcp-manage-channels",
    version: "1.0.0",
  });

  // Set up Rocket.Chat client
  const rcUrl = process.env.RC_URL ?? "http://localhost:3000";
  const rcClient = new RCClient(rcUrl);

  // Authenticate with Rocket.Chat
  const username = process.env.RC_USER;
  const password = process.env.RC_PASSWORD;

  if (!username || !password) {
    console.error("Error: RC_USER and RC_PASSWORD environment variables are required.");
    process.exit(1);
  }

  await authenticate(rcClient, username, password);

  // Register tools
  register_login(server, rcClient);
  register_channels_create(server, rcClient);
  register_channels_archive(server, rcClient);
  register_channels_unarchive(server, rcClient);
  register_channels_rename(server, rcClient);
  register_channels_setDescription(server, rcClient);
  register_channels_info(server, rcClient);
  register_channels_list(server, rcClient);

  // Connect via stdio transport
  const transport = new StdioServerTransport();
  await server.connect(transport);

  console.error(`rc-mcp-manage-channels MCP server running (8 tools)`);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
