/**
 * Tests for MCP Tool: set_status_and_notify
 *
 * Auto-generated by rc-mcp.
 * Validates Zod schema and handler function for this tool.
 */

import { describe, it, expect } from "vitest";
import { z } from "zod";
import { set_status_and_notifySchema, register_set_status_and_notify } from "../src/tools/set_status_and_notify.js";

describe("set_status_and_notify Zod Schema", () => {
  it("should have a valid Zod object schema", () => {
    expect(set_status_and_notifySchema).toBeDefined();
    expect(set_status_and_notifySchema instanceof z.ZodObject).toBe(true);
  });

  it("should enforce required fields (if any)", () => {
    // We dynamically check required fields from the parsed schema shape
    const shape = set_status_and_notifySchema.shape;
    const requiredKeys = Object.keys(shape).filter((key) => {
      const field = shape[key as keyof typeof shape];
      // A field is required if it's NOT explicitly optional
      return !(field instanceof z.ZodOptional);
    });

    if (requiredKeys.length === 0) {
      // If no required fields, an empty object should pass
      const result = set_status_and_notifySchema.safeParse({});
      expect(result.success).toBe(true);
    } else {
      // If there are required fields, an empty object should fail
      const result = set_status_and_notifySchema.safeParse({});
      expect(result.success).toBe(false);

      if (!result.success) {
        // Verify that the error mentions the missing required fields
        const errorPaths = result.error.errors.map((e) => e.path[0]);
        for (const reqKey of requiredKeys) {
          expect(errorPaths).toContain(reqKey);
        }
      }
    }
  });

  it("should reject invalid data types", () => {
    // Passing a complete mismatch should fail
    const resultString = set_status_and_notifySchema.safeParse("not-an-object");
    expect(resultString.success).toBe(false);

    const resultNumber = set_status_and_notifySchema.safeParse(42);
    expect(resultNumber.success).toBe(false);

    const resultArray = set_status_and_notifySchema.safeParse([]);
    expect(resultArray.success).toBe(false);
  });

  it("should export a register function for MCP server integration", () => {
    expect(register_set_status_and_notify).toBeDefined();
    expect(typeof register_set_status_and_notify).toBe("function");
  });
});
