/**
 * Tests for MCP Tool: setup_project_workspace
 *
 * Auto-generated by rc-mcp.
 * Validates Zod schema and handler function for this tool.
 */

import { describe, it, expect } from "vitest";
import { z } from "zod";
import { setup_project_workspaceSchema, register_setup_project_workspace } from "../src/tools/setup_project_workspace.js";

describe("setup_project_workspace Zod Schema", () => {
  it("should have a valid Zod object schema", () => {
    expect(setup_project_workspaceSchema).toBeDefined();
    expect(setup_project_workspaceSchema instanceof z.ZodObject).toBe(true);
  });

  it("should enforce required fields (if any)", () => {
    // We dynamically check required fields from the parsed schema shape
    const shape = setup_project_workspaceSchema.shape;
    const requiredKeys = Object.keys(shape).filter((key) => {
      const field = shape[key as keyof typeof shape];
      // A field is required if it's NOT explicitly optional
      return !(field instanceof z.ZodOptional);
    });

    if (requiredKeys.length === 0) {
      // If no required fields, an empty object should pass
      const result = setup_project_workspaceSchema.safeParse({});
      expect(result.success).toBe(true);
    } else {
      // If there are required fields, an empty object should fail
      const result = setup_project_workspaceSchema.safeParse({});
      expect(result.success).toBe(false);

      if (!result.success) {
        // Verify that the error mentions the missing required fields
        const errorPaths = result.error.errors.map((e) => e.path[0]);
        for (const reqKey of requiredKeys) {
          expect(errorPaths).toContain(reqKey);
        }
      }
    }
  });

  it("should reject invalid data types", () => {
    // Passing a complete mismatch should fail
    const resultString = setup_project_workspaceSchema.safeParse("not-an-object");
    expect(resultString.success).toBe(false);

    const resultNumber = setup_project_workspaceSchema.safeParse(42);
    expect(resultNumber.success).toBe(false);

    const resultArray = setup_project_workspaceSchema.safeParse([]);
    expect(resultArray.success).toBe(false);
  });

  it("should export a register function for MCP server integration", () => {
    expect(register_setup_project_workspace).toBeDefined();
    expect(typeof register_setup_project_workspace).toBe("function");
  });
});
