/**
 * MCP Tool: engagementdashboard_users_activeusers
 * Get Active Users
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/engagement-dashboard/users/active-users
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const engagementdashboard_users_activeusersSchema = z.object({
    start: z.string().describe("The start date."),
    end: z.string().describe("The end date.")
  });

export function register_engagementdashboard_users_activeusers(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "engagementdashboard_users_activeusers",
    "Get Active Users",
    engagementdashboard_users_activeusersSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/engagement-dashboard/users/active-users";
        const queryParts: string[] = [];
        if (params.start !== undefined) queryParts.push(`start=${encodeURIComponent(String(params.start))}`);
        if (params.end !== undefined) queryParts.push(`end=${encodeURIComponent(String(params.end))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
