/**
 * MCP Tool: roles_list
 * Get Roles
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/roles.list
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const roles_listSchema = z.object({});

export function register_roles_list(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "roles_list",
    "Get Roles",
    roles_listSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/roles.list";
        const result = await rcClient.get(apiPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
