/**
 * MCP Tool: roles_getUsersInRole
 * Get Users of a Role
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/roles.getUsersInRole
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const roles_getUsersInRoleSchema = z.object({
    role: z.string().describe("The ID of the role"),
    roomId: z.string().optional().describe("The room ID."),
    offset: z.number().optional().describe("Number of items to \"skip\" in the query, i.e. requests return count items, skipping the first offset items. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    count: z.number().optional().describe("How many items to return. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more.")
  });

export function register_roles_getUsersInRole(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "roles_getUsersInRole",
    "Get Users of a Role",
    roles_getUsersInRoleSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/roles.getUsersInRole";
        const queryParts: string[] = [];
        if (params.role !== undefined) queryParts.push(`role=${encodeURIComponent(String(params.role))}`);
        if (params.roomId !== undefined) queryParts.push(`roomId=${encodeURIComponent(String(params.roomId))}`);
        if (params.offset !== undefined) queryParts.push(`offset=${encodeURIComponent(String(params.offset))}`);
        if (params.count !== undefined) queryParts.push(`count=${encodeURIComponent(String(params.count))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
