/**
 * MCP Tool: roles_addUserToRole
 * Assign Role to User
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/roles.addUserToRole
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const roles_addUserToRoleSchema = z.object({
    roleId: z.string().optional().describe("The ID of an existing role."),
    username: z.string().describe("The user name."),
    roomId: z.string().optional().describe("The ID of the room where the user should be assigned a role, if it is a room role.")
  });

export function register_roles_addUserToRole(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "roles_addUserToRole",
    "Assign Role to User",
    roles_addUserToRoleSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/roles.addUserToRole";
        const body = {
          roleId: params.roleId,
          username: params.username,
          roomId: params.roomId
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
