/**
 * MCP Tool: roles_update
 * Update Role
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/roles.update
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const roles_updateSchema = z.object({
    roleId: z.string().describe("The role ID that you want to update."),
    name: z.string().describe("The updated name of the role."),
    scope: z.string().optional().describe("The updated  scope of the role. The scope can either be Users (user level) or Subscriptions (room level). The default value is `Users`."),
    description: z.string().optional().describe("Updated description for the role."),
    mandatory2fa: z.boolean().optional().describe("Whether the role should have a mandatory 2FA. The default value is `false`. If set to true, users assigned to this role are prompted to enter a 2FA code for certain activities.")
  });

export function register_roles_update(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "roles_update",
    "Update Role",
    roles_updateSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/roles.update";
        const body = {
          roleId: params.roleId,
          name: params.name,
          scope: params.scope,
          description: params.description,
          mandatory2fa: params.mandatory2fa
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
