/**
 * MCP Tool: roles_create
 * Create Role
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/roles.create
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const roles_createSchema = z.object({
    name: z.string().describe("Enter the new role's name."),
    scope: z.string().optional().describe("The new role's scope. The scope can either be Users (user level) or Subscriptions (room level). The default value is `Users`."),
    description: z.string().optional().describe("Enter a description for the new role."),
    mandatory2fa: z.boolean().optional().describe("Whether the role should have a mandatory 2FA. The default value is `false`. If set to true, users assigned to this role are prompted to enter a 2FA code for certain activities.")
  });

export function register_roles_create(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "roles_create",
    "Create Role",
    roles_createSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/roles.create";
        const body = {
          name: params.name,
          scope: params.scope,
          description: params.description,
          mandatory2fa: params.mandatory2fa
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
