/**
 * MCP Tool: settings__id
 * Get Setting
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/settings/{_id}
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const settings__idSchema = z.object({});

export function register_settings__id(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "settings__id",
    "Get Setting",
    settings__idSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/settings/{_id}";
        const result = await rcClient.get(apiPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
