/**
 * MCP Tool: statistics
 * Get Last Statistics
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/statistics
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const statisticsSchema = z.object({
    refresh: z.boolean().optional().describe("Set to true to refresh the statistics.")
  });

export function register_statistics(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "statistics",
    "Get Last Statistics",
    statisticsSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/statistics";
        const queryParts: string[] = [];
        if (params.refresh !== undefined) queryParts.push(`refresh=${encodeURIComponent(String(params.refresh))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
