/**
 * MCP Tool: users_setActiveStatus
 * Set User&#x27;s Status Active
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/users.setActiveStatus
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const users_setActiveStatusSchema = z.object({
    activeStatus: z.boolean().describe("The value of the active status."),
    userId: z.string().describe("The user ID whose status value is to be changed."),
    confirmRelinquish: z.boolean().optional().describe("Allows the user to be deactivated even if it is the last owner of a room. If `activeStatus=false` & `confirmRelinquish=true` and the user is the last remaining owner of a room, the oldest member of that room will be chosen as the new owner.")
  });

export function register_users_setActiveStatus(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "users_setActiveStatus",
    "Set User&#x27;s Status Active",
    users_setActiveStatusSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/users.setActiveStatus";
        const body = {
          activeStatus: params.activeStatus,
          userId: params.userId,
          confirmRelinquish: params.confirmRelinquish
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
