/**
 * MCP Tool: users_update
 * Update User Details
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/users.update
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const users_updateSchema = z.object({
    "x-2fa-method": z.string().describe("Enter the method with which you get the 2FA code. It can be `email`, `totp`, or `password`. This parameter is required if 2FA is enabled in your workspace."),
    userId: z.string().describe("The user ID to update. This value must not be empty."),
    data: z.object({
      name: z.string().optional().describe("The name of the user."),
      email: z.string().optional().describe("The email ID of the user."),
      password: z.string().optional().describe("The password for the user."),
      username: z.string().optional().describe("The username for the user."),
      active: z.boolean().optional().describe("Whether the user is active, which determines if they can login or not."),
      roles: z.array(z.string()).optional().describe("The roles the user has been assigned."),
      requirePasswordChange: z.boolean().optional().describe("Whether the user should be required to change their password when they login."),
      sendWelcomeEmail: z.boolean().optional().describe("Whether the user should get a welcome email."),
      freeSwitchExtension: z.string().optional().describe("The voice call extension."),
      verified: z.boolean().optional().describe("Whether the user's email address should be verified."),
      customFields: z.record(z.unknown()).optional().describe("Any custom fields the user should have on their account. To save custom fields, you must first define the custom fields in the admin panel (Manage > Workspace > Settings > Accounts > Registration > Custom Fields). For details on how to configure this field, see [Custom Fields](https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/accounts/custom-fields). For information on how to view the custom fields, see the [Get Users List](https://developer.rocket.chat/reference/api/rest-api/endpoints/user-management/users-endpoints/get-users-list) endpoint.")
    }).describe("The object that includes the user information to update with the following parameters. Note: If you provide an empty object, the user details are returned.")
  });

export function register_users_update(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "users_update",
    "Update User Details",
    users_updateSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/users.update";
        const body = {
          userId: params.userId,
          data: params.data
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
