#!/usr/bin/env node
/**
 * team-collaboration-mcp — Minimal MCP Server
 * Minimal MCP server for Rocket.Chat generated by rc-mcp.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 */

import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { RCClient } from "./rc-client.js";
import { authenticate } from "./auth.js";
import { register_dm_create } from "./tools/dm_create.js";
import { register_chat_postMessage } from "./tools/chat_postMessage.js";
import { register_rooms_createDiscussion } from "./tools/rooms_createDiscussion.js";
import { register_chat_getThreadMessages } from "./tools/chat_getThreadMessages.js";
import { register_chat_react } from "./tools/chat_react.js";
import { register_chat_pinMessage } from "./tools/chat_pinMessage.js";
import { register_chat_getPinnedMessages } from "./tools/chat_getPinnedMessages.js";
import { register_rooms_autocomplete_channelAndPrivate } from "./tools/rooms_autocomplete_channelAndPrivate.js";
import { register_login } from "./tools/login.js";

async function main() {
  // Initialize the MCP server
  const server = new McpServer({
    name: "team-collaboration-mcp",
    version: "1.0.0",
  });

  // Set up Rocket.Chat client
  const rcUrl = process.env.RC_URL ?? "http://localhost:3000";
  const rcClient = new RCClient(rcUrl);

  // Authenticate with Rocket.Chat
  const username = process.env.RC_USER;
  const password = process.env.RC_PASSWORD;

  if (!username || !password) {
    console.error("Error: RC_USER and RC_PASSWORD environment variables are required.");
    process.exit(1);
  }

  await authenticate(rcClient, username, password);

  // Register tools
  register_dm_create(server, rcClient);
  register_chat_postMessage(server, rcClient);
  register_rooms_createDiscussion(server, rcClient);
  register_chat_getThreadMessages(server, rcClient);
  register_chat_react(server, rcClient);
  register_chat_pinMessage(server, rcClient);
  register_chat_getPinnedMessages(server, rcClient);
  register_rooms_autocomplete_channelAndPrivate(server, rcClient);
  register_login(server, rcClient);

  // Connect via stdio transport
  const transport = new StdioServerTransport();
  await server.connect(transport);

  console.error(`team-collaboration-mcp MCP server running (9 tools)`);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
