#!/usr/bin/env node
/**
 * moderation — Minimal MCP Server
 * Minimal MCP server for Rocket.Chat generated by rc-mcp.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 *
 * Credentials: If RC_AUTH_TOKEN and RC_USER_ID are set in .env, the server
 * is pre-authenticated at startup. Individual tools can still override auth
 * by reading credentials from .env (pre-configured at generation time).
 */

import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { RCClient } from "./rc-client.js";
import { register_export_channel_history } from "./tools/export_channel_history.js";
import { register_archive_channel } from "./tools/archive_channel.js";
import { register_create_discussion_in_channel } from "./tools/create_discussion_in_channel.js";
import { register_channels_info } from "./tools/channels_info.js";
import { register_groups_history } from "./tools/groups_history.js";
import { register_groups_archive } from "./tools/groups_archive.js";
import { register_login } from "./tools/login.js";

async function main() {
  // Initialize the MCP server
  const server = new McpServer({
    name: "moderation",
    version: "1.0.0",
  });

  // RC_URL is resolved lazily from process.env on the first request.
  const rcClient = new RCClient();

  // If credentials were baked into .env during generation, pre-authenticate.
  const envAuthToken = process.env.RC_AUTH_TOKEN;
  const envUserId = process.env.RC_USER_ID;
  if (envAuthToken && envUserId) {
    rcClient.setAuth(envAuthToken, envUserId);
    console.error("Pre-authenticated from .env credentials.");
  }

  // Register tools
  register_export_channel_history(server, rcClient);
  register_archive_channel(server, rcClient);
  register_create_discussion_in_channel(server, rcClient);
  register_channels_info(server, rcClient);
  register_groups_history(server, rcClient);
  register_groups_archive(server, rcClient);
  register_login(server, rcClient);

  // Connect via stdio transport
  const transport = new StdioServerTransport();
  await server.connect(transport);

  console.error(`moderation MCP server ready (7 tools)`);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
