#!/usr/bin/env node
/**
 * standup — Minimal MCP Server
 * Minimal MCP server for Rocket.Chat generated by rc-mcp.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 *
 * Credentials: If RC_AUTH_TOKEN and RC_USER_ID are set in .env, the server
 * is pre-authenticated at startup. Individual tools can still override auth
 * by reading credentials from .env (pre-configured at generation time).
 */

import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { RCClient } from "./rc-client.js";
import { register_set_status_and_notify } from "./tools/set_status_and_notify.js";
import { register_send_message_to_channel } from "./tools/send_message_to_channel.js";
import { register_setup_project_workspace } from "./tools/setup_project_workspace.js";
import { register_login } from "./tools/login.js";

async function main() {
  // Initialize the MCP server
  const server = new McpServer({
    name: "standup",
    version: "1.0.0",
  });

  // RC_URL is resolved lazily from process.env on the first request.
  const rcClient = new RCClient();

  // If credentials were baked into .env during generation, pre-authenticate.
  const envAuthToken = process.env.RC_AUTH_TOKEN;
  const envUserId = process.env.RC_USER_ID;
  if (envAuthToken && envUserId) {
    rcClient.setAuth(envAuthToken, envUserId);
    console.error("Pre-authenticated from .env credentials.");
  }

  // Register tools
  register_set_status_and_notify(server, rcClient);
  register_send_message_to_channel(server, rcClient);
  register_setup_project_workspace(server, rcClient);
  register_login(server, rcClient);

  // Connect via stdio transport
  const transport = new StdioServerTransport();
  await server.connect(transport);

  console.error(`standup MCP server ready (4 tools)`);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
