/**
 * Rocket.Chat Authentication Helper
 *
 * Handles login and token management for the MCP server.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 */

import type { RCClient } from "./rc-client.js";

interface LoginResponse {
  status: string;
  data: {
    authToken: string;
    userId: string;
  };
}

/**
 * Authenticate with a Rocket.Chat server using username and password.
 * Sets the auth credentials on the RCClient instance.
 */
export async function authenticate(
  client: RCClient,
  username: string,
  password: string
): Promise<void> {
  const result = await client.post("/api/v1/login", {
    user: username,
    password: password,
  }) as LoginResponse;

  if (result.status !== "success" || !result.data?.authToken) {
    throw new Error("Rocket.Chat authentication failed. Check your credentials.");
  }

  client.setAuth(result.data.authToken, result.data.userId);
  console.error(`Authenticated as ${username} (userId: ${result.data.userId})`);
}
