#!/usr/bin/env node
/**
 * rc-mcp-read-messages — Minimal MCP Server
 * Minimal MCP server for Rocket.Chat: read-messages
 *
 * Auto-generated by rc-mcp — do not edit manually.
 */

import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { RCClient } from "./rc-client.js";
import { authenticate } from "./auth.js";
import { register_login } from "./tools/login.js";
import { register_channels_history } from "./tools/channels_history.js";
import { register_chat_search } from "./tools/chat_search.js";
import { register_chat_getMessage } from "./tools/chat_getMessage.js";

async function main() {
  // Initialize the MCP server
  const server = new McpServer({
    name: "rc-mcp-read-messages",
    version: "1.0.0",
  });

  // Set up Rocket.Chat client
  const rcUrl = process.env.RC_URL ?? "http://localhost:3000";
  const rcClient = new RCClient(rcUrl);

  // Authenticate with Rocket.Chat
  const username = process.env.RC_USER;
  const password = process.env.RC_PASSWORD;

  if (!username || !password) {
    console.error("Error: RC_USER and RC_PASSWORD environment variables are required.");
    process.exit(1);
  }

  await authenticate(rcClient, username, password);

  // Register tools
  register_login(server, rcClient);
  register_channels_history(server, rcClient);
  register_chat_search(server, rcClient);
  register_chat_getMessage(server, rcClient);

  // Connect via stdio transport
  const transport = new StdioServerTransport();
  await server.connect(transport);

  console.error(`rc-mcp-read-messages MCP server running (4 tools)`);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
