#!/usr/bin/env node
/**
 * customer-support-bot-mcp — Minimal MCP Server
 * Minimal MCP server for Rocket.Chat generated by rc-mcp.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 */

import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { RCClient } from "./rc-client.js";
import { authenticate } from "./auth.js";
import { register_livechat_visitor } from "./tools/livechat_visitor.js";
import { register_livechat_room_forward } from "./tools/livechat_room_forward.js";
import { register_livechat_visitor_department_transfer } from "./tools/livechat_visitor_department_transfer.js";
import { register_cannedresponses_get } from "./tools/cannedresponses_get.js";
import { register_chat_postMessage } from "./tools/chat_postMessage.js";
import { register_livechat_department_autocomplete } from "./tools/livechat_department_autocomplete.js";
import { register_livechat_agent_info_rid_token } from "./tools/livechat_agent_info_rid_token.js";
import { register_login } from "./tools/login.js";

async function main() {
  // Initialize the MCP server
  const server = new McpServer({
    name: "customer-support-bot-mcp",
    version: "1.0.0",
  });

  // Set up Rocket.Chat client
  const rcUrl = process.env.RC_URL ?? "http://localhost:3000";
  const rcClient = new RCClient(rcUrl);

  // Authenticate with Rocket.Chat
  const username = process.env.RC_USER;
  const password = process.env.RC_PASSWORD;

  if (!username || !password) {
    console.error("Error: RC_USER and RC_PASSWORD environment variables are required.");
    process.exit(1);
  }

  await authenticate(rcClient, username, password);

  // Register tools
  register_livechat_visitor(server, rcClient);
  register_livechat_room_forward(server, rcClient);
  register_livechat_visitor_department_transfer(server, rcClient);
  register_cannedresponses_get(server, rcClient);
  register_chat_postMessage(server, rcClient);
  register_livechat_department_autocomplete(server, rcClient);
  register_livechat_agent_info_rid_token(server, rcClient);
  register_login(server, rcClient);

  // Connect via stdio transport
  const transport = new StdioServerTransport();
  await server.connect(transport);

  console.error(`customer-support-bot-mcp MCP server running (8 tools)`);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
