#!/usr/bin/env node
/**
 * rc-mcp-manage-users — Minimal MCP Server
 * Minimal MCP server for Rocket.Chat: manage-users
 *
 * Auto-generated by rc-mcp — do not edit manually.
 */

import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { RCClient } from "./rc-client.js";
import { authenticate } from "./auth.js";
import { register_login } from "./tools/login.js";
import { register_users_create } from "./tools/users_create.js";
import { register_users_update } from "./tools/users_update.js";
import { register_users_delete } from "./tools/users_delete.js";
import { register_users_info } from "./tools/users_info.js";
import { register_users_list } from "./tools/users_list.js";

async function main() {
  // Initialize the MCP server
  const server = new McpServer({
    name: "rc-mcp-manage-users",
    version: "1.0.0",
  });

  // Set up Rocket.Chat client
  const rcUrl = process.env.RC_URL ?? "http://localhost:3000";
  const rcClient = new RCClient(rcUrl);

  // Authenticate with Rocket.Chat
  const username = process.env.RC_USER;
  const password = process.env.RC_PASSWORD;

  if (!username || !password) {
    console.error("Error: RC_USER and RC_PASSWORD environment variables are required.");
    process.exit(1);
  }

  await authenticate(rcClient, username, password);

  // Register tools
  register_login(server, rcClient);
  register_users_create(server, rcClient);
  register_users_update(server, rcClient);
  register_users_delete(server, rcClient);
  register_users_info(server, rcClient);
  register_users_list(server, rcClient);

  // Connect via stdio transport
  const transport = new StdioServerTransport();
  await server.connect(transport);

  console.error(`rc-mcp-manage-users MCP server running (6 tools)`);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
