/**
 * Tests for MCP Tool: users_info
 *
 * Auto-generated by rc-mcp.
 * Provides thorough validation of the generated Zod schema.
 */

import { describe, it, expect } from "vitest";
import { z } from "zod";
import { users_infoSchema } from "../src/tools/users_info.js";

describe("users_info Zod Schema", () => {
  it("should have a valid Zod object schema", () => {
    expect(users_infoSchema).toBeDefined();
    expect(users_infoSchema instanceof z.ZodObject).toBe(true);
  });

  it("should enforce required fields (if any)", () => {
    // We dynamically check required fields from the parsed schema shape
    const shape = users_infoSchema.shape;
    const requiredKeys = Object.keys(shape).filter((key) => {
      const field = shape[key as keyof typeof shape];
      // A field is required if it's NOT explicitly optional
      return !(field instanceof z.ZodOptional);
    });

    if (requiredKeys.length === 0) {
      // If no required fields, an empty object should pass
      const result = users_infoSchema.safeParse({});
      expect(result.success).toBe(true);
    } else {
      // If there are required fields, an empty object should fail
      const result = users_infoSchema.safeParse({});
      expect(result.success).toBe(false);

      if (!result.success) {
        // Verify that the error mentions the missing required fields
        const errorPaths = result.error.errors.map((e) => e.path[0]);
        for (const reqKey of requiredKeys) {
          expect(errorPaths).toContain(reqKey);
        }
      }
    }
  });

  it("should reject invalid data types", () => {
    // Passing a complete mismatch should fail
    const resultString = users_infoSchema.safeParse("not-an-object");
    expect(resultString.success).toBe(false);

    const resultNumber = users_infoSchema.safeParse(42);
    expect(resultNumber.success).toBe(false);

    const resultArray = users_infoSchema.safeParse([]);
    expect(resultArray.success).toBe(false);
  });
});
