/**
 * MCP Tool: archive_channel
 * Resolve a channel by name and archive it. Combines lookup + archive into one operation.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/rooms.info
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const archive_channelSchema = z.object({
    channelName: z.string().describe("Channel name to archive")
  });

export function register_archive_channel(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "archive_channel",
    "Resolve a channel by name and archive it. Combines lookup + archive into one operation.",
    archive_channelSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed

        // Store results from each step for parameter wiring
        const stepResults: unknown[] = [];

        // ── Step 1: Look up channel by name ──
        const step0Params: Record<string, unknown> = {};
        if (params.channelName !== undefined) step0Params["roomName"] = params.channelName;
        let step0Result;
        {
          const step0Query = Object.entries(step0Params).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join("&");
          const step0Path = step0Query ? `/api/v1/rooms.info?${step0Query}` : "/api/v1/rooms.info";
          step0Result = await rcClient.get(step0Path);
        }
        stepResults.push(step0Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 2: Archive the channel ──
        const step1Params: Record<string, unknown> = {};
        step1Params["roomId"] = (stepResults[0] as any)?.room?._id;
        let step1Result;
        try {
          step1Result = await rcClient.post("/api/v1/channels.archive", step1Params);
        } catch (err) {
          // Fallback to post-api-v1-groups.archive
          step1Result = await rcClient.post("/api/v1/groups.archive", step1Params);
        }
        stepResults.push(step1Result);

        // Return the final result from step 2
        return { content: [{ type: "text" as const, text: JSON.stringify(step1Result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Workflow "${"archive_channel"}" failed: ${message}` }], isError: true };
      }
    }
  );
}
