/**
 * MCP Tool: channels_info
 * Get Channel Information. GET channels.info API wrapper.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/channels.info
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const channels_infoSchema = z.object({
    roomId: z.string().optional().describe("The room ID. It is required if the `roomName` is not provided."),
    roomName: z.string().optional().describe("The room name.  It is required if the `roomId` is not provided.")
  });

export function register_channels_info(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "channels_info",
    "Get Channel Information. GET channels.info API wrapper.",
    channels_infoSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed
        const apiPath = "/api/v1/channels.info";
        const queryParts: string[] = [];
        if (params.roomId !== undefined) queryParts.push(`roomId=${encodeURIComponent(String(params.roomId))}`);
        if (params.roomName !== undefined) queryParts.push(`roomName=${encodeURIComponent(String(params.roomName))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        let message = error instanceof Error ? error.message : String(error);
        if (message.includes("RC API Error")) {
          const match = message.match(/RC API Error \[(\d+)\] .*?: (.*)/);
          if (match) {
            message = `HTTP ${match[1]}: ${match[2]}`;
          }
        }
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
