/**
 * MCP Tool: create_discussion_in_channel
 * Resolve a channel by name and create a threaded discussion in it.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/rooms.info
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const create_discussion_in_channelSchema = z.object({
    channelName: z.string().describe("Parent channel name"),
    discussionName: z.string().describe("Title of the discussion"),
    initialMessage: z.string().optional().describe("Initial message for the discussion")
  });

export function register_create_discussion_in_channel(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "create_discussion_in_channel",
    "Resolve a channel by name and create a threaded discussion in it.",
    create_discussion_in_channelSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed

        // Store results from each step for parameter wiring
        const stepResults: unknown[] = [];

        // ── Step 1: Look up channel by name ──
        const step0Params: Record<string, unknown> = {};
        if (params.channelName !== undefined) step0Params["roomName"] = params.channelName;
        let step0Result;
        {
          const step0Query = Object.entries(step0Params).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join("&");
          const step0Path = step0Query ? `/api/v1/rooms.info?${step0Query}` : "/api/v1/rooms.info";
          step0Result = await rcClient.get(step0Path);
        }
        stepResults.push(step0Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 2: Create a discussion in the resolved channel ──
        const step1Params: Record<string, unknown> = {};
        if (params.discussionName !== undefined) step1Params["t_name"] = params.discussionName;
        if (params.initialMessage !== undefined) step1Params["reply"] = params.initialMessage;
        step1Params["prid"] = (stepResults[0] as any)?.room?._id;
        let step1Result;
        step1Result = await rcClient.post("/api/v1/rooms.createDiscussion", step1Params);
        stepResults.push(step1Result);

        // Return the final result from step 2
        return { content: [{ type: "text" as const, text: JSON.stringify(step1Result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Workflow "${"create_discussion_in_channel"}" failed: ${message}` }], isError: true };
      }
    }
  );
}
