/**
 * MCP Tool: export_channel_history
 * Resolve a room by name and fetch its message history. Spans rooms + messaging.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/rooms.info
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const export_channel_historySchema = z.object({
    channelName: z.string().describe("Room/Channel name to export history from"),
    count: z.number().optional().describe("Number of messages to fetch (default: 50)")
  });

export function register_export_channel_history(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "export_channel_history",
    "Resolve a room by name and fetch its message history. Spans rooms + messaging.",
    export_channel_historySchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed

        // Store results from each step for parameter wiring
        const stepResults: unknown[] = [];

        // ── Step 1: Look up room by name ──
        const step0Params: Record<string, unknown> = {};
        if (params.channelName !== undefined) step0Params["roomName"] = params.channelName;
        let step0Result;
        {
          const step0Query = Object.entries(step0Params).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join("&");
          const step0Path = step0Query ? `/api/v1/rooms.info?${step0Query}` : "/api/v1/rooms.info";
          step0Result = await rcClient.get(step0Path);
        }
        stepResults.push(step0Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 2: Fetch message history ──
        const step1Params: Record<string, unknown> = {};
        if (params.count !== undefined) step1Params["count"] = params.count;
        step1Params["roomId"] = (stepResults[0] as any)?.room?._id;
        let step1Result;
        try {
          {
            const step1Query = Object.entries(step1Params).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join("&");
            const step1Path = step1Query ? `/api/v1/channels.history?${step1Query}` : "/api/v1/channels.history";
            step1Result = await rcClient.get(step1Path);
          }
        } catch (err) {
          // Fallback to get-api-v1-groups.history
          {
            const step1Query = Object.entries(step1Params).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join("&");
            const step1Path = step1Query ? `/api/v1/groups.history?${step1Query}` : "/api/v1/groups.history";
            step1Result = await rcClient.get(step1Path);
          }
        }
        stepResults.push(step1Result);

        // Return the final result from step 2
        return { content: [{ type: "text" as const, text: JSON.stringify(step1Result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Workflow "${"export_channel_history"}" failed: ${message}` }], isError: true };
      }
    }
  );
}
