/**
 * MCP Tool: groups_history
 * Get Group History. GET groups.history API wrapper. Requires: roomId.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/groups.history
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const groups_historySchema = z.object({
    roomId: z.string().describe("The room id."),
    latest: z.string().optional().describe("The end of the time range of messages to retrieve. The default value is the current date and time."),
    oldest: z.string().optional().describe("The start of the time range to retrieve messages."),
    inclusive: z.boolean().optional().describe("Whether messages sent on the latest and oldest dates should be included. The default value is false."),
    unreads: z.boolean().optional().describe("Whether unread messages should be included in the response. The default value is false."),
    offset: z.number().optional().describe("Number of items to \"skip\" in the query, i.e. requests return count items, skipping the first offset items. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    count: z.number().optional().describe("The number of items to return. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more.")
  });

export function register_groups_history(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "groups_history",
    "Get Group History. GET groups.history API wrapper. Requires: roomId.",
    groups_historySchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed
        const apiPath = "/api/v1/groups.history";
        const queryParts: string[] = [];
        if (params.roomId !== undefined) queryParts.push(`roomId=${encodeURIComponent(String(params.roomId))}`);
        if (params.latest !== undefined) queryParts.push(`latest=${encodeURIComponent(String(params.latest))}`);
        if (params.oldest !== undefined) queryParts.push(`oldest=${encodeURIComponent(String(params.oldest))}`);
        if (params.inclusive !== undefined) queryParts.push(`inclusive=${encodeURIComponent(String(params.inclusive))}`);
        if (params.unreads !== undefined) queryParts.push(`unreads=${encodeURIComponent(String(params.unreads))}`);
        if (params.offset !== undefined) queryParts.push(`offset=${encodeURIComponent(String(params.offset))}`);
        if (params.count !== undefined) queryParts.push(`count=${encodeURIComponent(String(params.count))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        let message = error instanceof Error ? error.message : String(error);
        if (message.includes("RC API Error")) {
          const match = message.match(/RC API Error \[(\d+)\] .*?: (.*)/);
          if (match) {
            message = `HTTP ${match[1]}: ${match[2]}`;
          }
        }
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
