/**
 * MCP Tool: groups_archive
 * Archive a Group. POST groups.archive API wrapper. Requires: roomId.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/groups.archive
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const groups_archiveSchema = z.object({
    roomId: z.string().describe("The group ID that you want to archive. You can find the IDs by using any of the following endpoints: * <a href='https://developer.rocket.chat/apidocs/get-list-of-user-groups' target='_blank'>Get List of User Groups</a>: This endpoint returns all private channels in the workspace, if you have the required permissions to view them. * <a href='https://developer.rocket.chat/apidocs/get-groups' target='_blank'>Get Groups</a>: This endpoint returns the private channels that you are a member of.")
  });

export function register_groups_archive(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "groups_archive",
    "Archive a Group. POST groups.archive API wrapper. Requires: roomId.",
    groups_archiveSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed
        const apiPath = "/api/v1/groups.archive";
        const body = {
          roomId: params.roomId
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        let message = error instanceof Error ? error.message : String(error);
        if (message.includes("RC API Error")) {
          const match = message.match(/RC API Error \[(\d+)\] .*?: (.*)/);
          if (match) {
            message = `HTTP ${match[1]}: ${match[2]}`;
          }
        }
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
