/**
 * MCP Tool: create_project_channel
 * Create a new channel and configure it with a description and topic in one operation.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/channels.create
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const create_project_channelSchema = z.object({
    channelName: z.string().describe("Name for the new channel"),
    description: z.string().optional().describe("Channel description"),
    topic: z.string().optional().describe("Channel topic")
  });

export function register_create_project_channel(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "create_project_channel",
    "Create a new channel and configure it with a description and topic in one operation.",
    create_project_channelSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed

        // Store results from each step for parameter wiring
        const stepResults: unknown[] = [];

        // ── Step 1: Create the channel ──
        const step0Params: Record<string, unknown> = {};
        if (params.channelName !== undefined) step0Params["name"] = params.channelName;
        let step0Result;
        step0Result = await rcClient.post("/api/v1/channels.create", step0Params);
        stepResults.push(step0Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 2: Set channel description ──
        const step1Params: Record<string, unknown> = {};
        if (params.description !== undefined) step1Params["description"] = params.description;
        step1Params["roomId"] = (stepResults[0] as any)?.channel?._id;
        let step1Result;
        step1Result = await rcClient.post("/api/v1/channels.setDescription", step1Params);
        stepResults.push(step1Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 3: Set channel topic ──
        const step2Params: Record<string, unknown> = {};
        if (params.topic !== undefined) step2Params["topic"] = params.topic;
        step2Params["roomId"] = (stepResults[0] as any)?.channel?._id;
        let step2Result;
        step2Result = await rcClient.post("/api/v1/channels.setTopic", step2Params);
        stepResults.push(step2Result);

        // Return the final result from step 3
        return { content: [{ type: "text" as const, text: JSON.stringify(step2Result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Workflow "${"create_project_channel"}" failed: ${message}` }], isError: true };
      }
    }
  );
}
