/**
 * MCP Tool: setup_webhook_integration
 * Resolve a room by name and create an incoming webhook integration for it. Spans integrations + rooms.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/rooms.info
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const setup_webhook_integrationSchema = z.object({
    channelName: z.string().describe("Room/Channel name to set up the webhook for"),
    webhookName: z.string().describe("Name for the webhook integration")
  });

export function register_setup_webhook_integration(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "setup_webhook_integration",
    "Resolve a room by name and create an incoming webhook integration for it. Spans integrations + rooms.",
    setup_webhook_integrationSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed

        // Store results from each step for parameter wiring
        const stepResults: unknown[] = [];

        // ── Step 1: Look up target room by name ──
        const step0Params: Record<string, unknown> = {};
        if (params.channelName !== undefined) step0Params["roomName"] = params.channelName;
        let step0Result;
        {
          const step0Query = Object.entries(step0Params).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join("&");
          const step0Path = step0Query ? `/api/v1/rooms.info?${step0Query}` : "/api/v1/rooms.info";
          step0Result = await rcClient.get(step0Path);
        }
        stepResults.push(step0Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 2: Create incoming webhook integration ──
        const step1Params: Record<string, unknown> = {};
        if (params.webhookName !== undefined) step1Params["name"] = params.webhookName;
        step1Params["channel"] = (stepResults[0] as any)?.room?._id;
        step1Params["type"] = "webhook-incoming";
        step1Params["username"] = "bot";
        step1Params["scriptEnabled"] = false;
        step1Params["enabled"] = true;
        let step1Result;
        step1Result = await rcClient.post("/api/v1/integrations.create", step1Params);
        stepResults.push(step1Result);

        // Return the final result from step 2
        return { content: [{ type: "text" as const, text: JSON.stringify(step1Result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Workflow "${"setup_webhook_integration"}" failed: ${message}` }], isError: true };
      }
    }
  );
}
