/**
 * MCP Tool: channels_create
 * Create Channel
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/channels.create
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const channels_createSchema = z.object({
    name: z.string().describe("The name of the channel."),
    members: z.array(z.string()).optional().describe("An array of the users to be added to the channel when it is created."),
    readOnly: z.boolean().optional().describe("Set if the channel is read only or not. It is `false` by default."),
    excludeSelf: z.boolean().optional().describe("If set to true, the user calling the endpoint is not automatically added as a member of the channel. The default `value` is false."),
    customFields: z.record(z.unknown()).optional().describe("If you have defined custom fields for your workspace, you can provide them in this object parameter. For details, see the <a href='https://docs.rocket.chat/docs/custom-fields' target='_blank'>Custom Fields</a> document."),
    extraData: z.record(z.unknown()).optional().describe("Enter the following details for the object: - `broadcast`: Whether the channel should be a broadcast room. - `encrypted`: Whether the channel should be encrypted. - `teamId`: Enter an existing team ID for this channel. You need the `create-team-channel` permission to add a team to a channel.  For more information, see <a href='https://docs.rocket.chat/use-rocket.chat/user-guides/rooms/channels#channel-privacy-and-encryption' target='_blank'>Channels</a>")
  });

export function register_channels_create(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "channels_create",
    "Create Channel",
    channels_createSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/channels.create";
        const body = {
          name: params.name,
          members: params.members,
          readOnly: params.readOnly,
          excludeSelf: params.excludeSelf,
          customFields: params.customFields,
          extraData: params.extraData
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
