/**
 * MCP Tool: channels_rename
 * Rename a Channel
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/channels.rename
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const channels_renameSchema = z.object({
    roomId: z.string().describe("The channel's ID."),
    name: z.string().describe("The new name of the channel. It can not be the same as the current name.")
  });

export function register_channels_rename(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "channels_rename",
    "Rename a Channel",
    channels_renameSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/channels.rename";
        const body = {
          roomId: params.roomId,
          name: params.name
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
