/**
 * MCP Tool: channels_unarchive
 * Unarchive a Channel
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/channels.unarchive
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const channels_unarchiveSchema = z.object({
    roomId: z.string().optional().describe("The channel ID that you want to unarchive.")
  });

export function register_channels_unarchive(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "channels_unarchive",
    "Unarchive a Channel",
    channels_unarchiveSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/channels.unarchive";
        const body = {
          roomId: params.roomId
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
