/**
 * MCP Tool: channels_setDescription
 * Set Channel Description
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/channels.setDescription
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const channels_setDescriptionSchema = z.object({
    roomId: z.string().describe("The channel ID."),
    description: z.string().describe("The description to set for the channel.")
  });

export function register_channels_setDescription(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "channels_setDescription",
    "Set Channel Description",
    channels_setDescriptionSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/channels.setDescription";
        const body = {
          roomId: params.roomId,
          description: params.description
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
