/**
 * MCP Tool: users_create
 * Create User
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/users.create
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const users_createSchema = z.object({
    name: z.string().describe("The display name of the user."),
    email: z.string().describe("The email address for the user."),
    password: z.string().describe("The password for the user."),
    username: z.string().describe("The username for the user."),
    active: z.boolean().optional().describe("Set the users' active status.  If the user is deactivated, they can not login. By default, the user is active."),
    nickname: z.string().optional().describe("The nickname for the user. "),
    bio: z.string().optional().describe("The bio for the user."),
    joinDefaultChannels: z.boolean().optional().describe("Select whether users should automatically join default channels once they are created. By default, it is set to `true`."),
    statusText: z.string().optional().describe("The status text of the user."),
    roles: z.array(z.string()).optional().describe("The roles to be assigned to this user. If it is not specified, the `user` role is assigned by default. **Note:** * For default roles, the role name and ID are the same. For custom roles, the name and ID are different.  * If you are setting a custom role for a user, make sure to enter the custom role ID, and not the role name. Refer to [Roles](https://docs.rocket.chat/use-rocket.chat/workspace-administration/permissions#roles) for more information."),
    requirePasswordChange: z.boolean().optional().describe("Should the user be required to change their password when they login? It is set to `false` by default"),
    setRandomPassword: z.boolean().optional().describe("Should the user be assigned a random password once they are created? It is set to `false` by defualt."),
    sendWelcomeEmail: z.boolean().optional().describe("Should the user get a welcome email? It is set to `true` by default."),
    verified: z.boolean().optional().describe("Should the user's email address be verified when created? It is set to `false` by default."),
    customFields: z.record(z.unknown()).optional().describe("A valid JSON object of key-value pairs consisting of additional fields to be added during user registration. By default, the value is `undefined`. To save custom fields, you must first define them in the [workspace admin settings](https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/accounts/custom-fields). For information on how to view the custom fields, see the [Get Users List](https://developer.rocket.chat/reference/api/rest-api/endpoints/user-management/users-endpoints/get-users-list) endpoint.")
  });

export function register_users_create(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "users_create",
    "Create User",
    users_createSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/users.create";
        const body = {
          name: params.name,
          email: params.email,
          password: params.password,
          username: params.username,
          active: params.active,
          nickname: params.nickname,
          bio: params.bio,
          joinDefaultChannels: params.joinDefaultChannels,
          statusText: params.statusText,
          roles: params.roles,
          requirePasswordChange: params.requirePasswordChange,
          setRandomPassword: params.setRandomPassword,
          sendWelcomeEmail: params.sendWelcomeEmail,
          verified: params.verified,
          customFields: params.customFields
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
