/**
 * MCP Tool: users_info
 * Get User&#x27;s Info
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/users.info
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const users_infoSchema = z.object({
    userId: z.string().describe("The `userId` of the user. Alternatively, you can use the `username` parameter and value."),
    includeUserRooms: z.boolean().optional().describe("Enter whether or not the rooms that the user is a member of are included in the response. To view the list of rooms, you need the `view-other-user-channels` permission."),
    importId: z.string().optional().describe("You can use this parameter to search for users that were imported from external channels, such as Slack. You can also get the value of the import ID using this endpoint if you have the `view-full-other-user-info` permission.")
  });

export function register_users_info(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "users_info",
    "Get User&#x27;s Info",
    users_infoSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/users.info";
        const queryParts: string[] = [];
        if (params.userId !== undefined) queryParts.push(`userId=${encodeURIComponent(String(params.userId))}`);
        if (params.includeUserRooms !== undefined) queryParts.push(`includeUserRooms=${encodeURIComponent(String(params.includeUserRooms))}`);
        if (params.importId !== undefined) queryParts.push(`importId=${encodeURIComponent(String(params.importId))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
