/**
 * MCP Tool: users_delete
 * Delete User
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/users.delete
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const users_deleteSchema = z.object({
    userId: z.string().describe("The `userId` of the user. Alternatively, you can use the `username` property and value."),
    confirmRelinquish: z.boolean().optional().describe("Deletes the user, even if they are the last owner of a room. By default, it is set to `false`.")
  });

export function register_users_delete(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "users_delete",
    "Delete User",
    users_deleteSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/users.delete";
        const body = {
          userId: params.userId,
          confirmRelinquish: params.confirmRelinquish
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
