/**
 * MCP Tool: users_list
 * Get Users List
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/users.list
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const users_listSchema = z.object({
    query: z.string().optional().describe("This parameter allows you to use [MongoDB query](https://www.mongodb.com/docs/manual/reference/operator/query/) operators to search for specific data. For example, to query users with a name that contains the letter \"g\": query=`{ \"name\": { \"$regex\": \"g\" } }`. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#query-and-fields) to learn more. "),
    fields: z.string().optional().describe(" This parameter accepts a JSON object with properties that have a value of 1 or 0 to include or exclude them in the response. For example, to only retrieve the usernames of users: fields=`{ \"username\": 1 }`. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#query-and-fields) to learn more."),
    offset: z.number().optional().describe("Number of items to \"skip\" in the query, i.e. requests return count items, skipping the first offset items. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    count: z.number().optional().describe("How many items to return. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    sort: z.string().optional().describe("Sort the users in ascending (`1`) or descending (`-1`) order. The value must be entered as a JSON string. The options are as follows:  * `status`: Sort by users' status. For example, `sort={\"status\":1}` (this maps to the `active` status).  * `createdAt`: Sort by the time of user creation. For example, `sort={\"createdAt\":-1}`  * `sort`: Sort by user name. For example, `sort={\"name\":1}`")
  });

export function register_users_list(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "users_list",
    "Get Users List",
    users_listSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/users.list";
        const queryParts: string[] = [];
        if (params.query !== undefined) queryParts.push(`query=${encodeURIComponent(String(params.query))}`);
        if (params.fields !== undefined) queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
        if (params.offset !== undefined) queryParts.push(`offset=${encodeURIComponent(String(params.offset))}`);
        if (params.count !== undefined) queryParts.push(`count=${encodeURIComponent(String(params.count))}`);
        if (params.sort !== undefined) queryParts.push(`sort=${encodeURIComponent(String(params.sort))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
