/**
 * MCP Tool: channels_history
 * Get Channel History
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/channels.history
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const channels_historySchema = z.object({
    roomId: z.string().optional().describe("The room ID. It is required if the `roomName` is not provided."),
    roomName: z.string().optional().describe("The room name.  It is required if the `roomId` is not provided."),
    sort: z.string().optional().describe("List of fields to order by, and in which direction. This is a JSON object, with properties listed in desired order, with values of 1 for ascending, or -1 for descending. For example, {\"value\": -1, \"_id\": 1}. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    count: z.number().optional().describe("The number of items to return. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    offset: z.number().optional().describe("Number of items to \"skip\" in the query, i.e. requests return count items, skipping the first offset items. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    latest: z.string().optional().describe("The end of time range of messages to retrieve. The default value is the current date and time."),
    oldest: z.string().optional().describe("The start of the time range of messages to retrieve"),
    inclusive: z.boolean().optional().describe("Whether messages which land on the latest and oldest dates should be included. The default value is false."),
    showThreadMessages: z.boolean().optional().describe("Whether thread messages should be included in the response"),
    unreads: z.boolean().optional().describe("Whether the number of unread messages should be included. The default value is false.")
  });

export function register_channels_history(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "channels_history",
    "Get Channel History",
    channels_historySchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/channels.history";
        const queryParts: string[] = [];
        if (params.roomId !== undefined) queryParts.push(`roomId=${encodeURIComponent(String(params.roomId))}`);
        if (params.roomName !== undefined) queryParts.push(`roomName=${encodeURIComponent(String(params.roomName))}`);
        if (params.sort !== undefined) queryParts.push(`sort=${encodeURIComponent(String(params.sort))}`);
        if (params.count !== undefined) queryParts.push(`count=${encodeURIComponent(String(params.count))}`);
        if (params.offset !== undefined) queryParts.push(`offset=${encodeURIComponent(String(params.offset))}`);
        if (params.latest !== undefined) queryParts.push(`latest=${encodeURIComponent(String(params.latest))}`);
        if (params.oldest !== undefined) queryParts.push(`oldest=${encodeURIComponent(String(params.oldest))}`);
        if (params.inclusive !== undefined) queryParts.push(`inclusive=${encodeURIComponent(String(params.inclusive))}`);
        if (params.showThreadMessages !== undefined) queryParts.push(`showThreadMessages=${encodeURIComponent(String(params.showThreadMessages))}`);
        if (params.unreads !== undefined) queryParts.push(`unreads=${encodeURIComponent(String(params.unreads))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
