/**
 * MCP Tool: chat_getMessage
 * Get Message
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/chat.getMessage
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const chat_getMessageSchema = z.object({
    msgId: z.string().describe("The message ID.")
  });

export function register_chat_getMessage(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "chat_getMessage",
    "Get Message",
    chat_getMessageSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/chat.getMessage";
        const queryParts: string[] = [];
        if (params.msgId !== undefined) queryParts.push(`msgId=${encodeURIComponent(String(params.msgId))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
