/**
 * MCP Tool: chat_search
 * Search Message
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/chat.search
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const chat_searchSchema = z.object({
    count: z.number().optional().describe("The number of items to return.  Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    offset: z.number().optional().describe("Number of items to \"skip\" in the query, i.e. requests return count items, skipping the first offset items. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    roomId: z.string().describe("The room ID."),
    searchText: z.string().describe("The text to search for in messages.")
  });

export function register_chat_search(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "chat_search",
    "Search Message",
    chat_searchSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/chat.search";
        const queryParts: string[] = [];
        if (params.count !== undefined) queryParts.push(`count=${encodeURIComponent(String(params.count))}`);
        if (params.offset !== undefined) queryParts.push(`offset=${encodeURIComponent(String(params.offset))}`);
        if (params.roomId !== undefined) queryParts.push(`roomId=${encodeURIComponent(String(params.roomId))}`);
        if (params.searchText !== undefined) queryParts.push(`searchText=${encodeURIComponent(String(params.searchText))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
