/**
 * Tests for MCP Tool: setup_webhook_integration
 *
 * Auto-generated by rc-mcp.
 * Validates Zod schema and handler function for this tool.
 */

import { describe, it, expect } from "vitest";
import { z } from "zod";
import { setup_webhook_integrationSchema, register_setup_webhook_integration } from "../src/tools/setup_webhook_integration.js";

describe("setup_webhook_integration Zod Schema", () => {
  it("should have a valid Zod object schema", () => {
    expect(setup_webhook_integrationSchema).toBeDefined();
    expect(setup_webhook_integrationSchema instanceof z.ZodObject).toBe(true);
  });

  it("should enforce required fields (if any)", () => {
    // We dynamically check required fields from the parsed schema shape
    const shape = setup_webhook_integrationSchema.shape;
    const requiredKeys = Object.keys(shape).filter((key) => {
      const field = shape[key as keyof typeof shape];
      // A field is required if it's NOT explicitly optional
      return !(field instanceof z.ZodOptional);
    });

    if (requiredKeys.length === 0) {
      // If no required fields, an empty object should pass
      const result = setup_webhook_integrationSchema.safeParse({});
      expect(result.success).toBe(true);
    } else {
      // If there are required fields, an empty object should fail
      const result = setup_webhook_integrationSchema.safeParse({});
      expect(result.success).toBe(false);

      if (!result.success) {
        // Verify that the error mentions the missing required fields
        const errorPaths = result.error.errors.map((e) => e.path[0]);
        for (const reqKey of requiredKeys) {
          expect(errorPaths).toContain(reqKey);
        }
      }
    }
  });

  it("should reject invalid data types", () => {
    // Passing a complete mismatch should fail
    const resultString = setup_webhook_integrationSchema.safeParse("not-an-object");
    expect(resultString.success).toBe(false);

    const resultNumber = setup_webhook_integrationSchema.safeParse(42);
    expect(resultNumber.success).toBe(false);

    const resultArray = setup_webhook_integrationSchema.safeParse([]);
    expect(resultArray.success).toBe(false);
  });

  it("should export a register function for MCP server integration", () => {
    expect(register_setup_webhook_integration).toBeDefined();
    expect(typeof register_setup_webhook_integration).toBe("function");
  });
});
