#!/usr/bin/env node
/**
 * workspace-admin-mcp — Minimal MCP Server
 * Minimal MCP server for Rocket.Chat generated by rc-mcp.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 */

import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { RCClient } from "./rc-client.js";
import { authenticate } from "./auth.js";
import { register_statistics } from "./tools/statistics.js";
import { register_engagementdashboard_users_activeusers } from "./tools/engagementdashboard_users_activeusers.js";
import { register_users_list } from "./tools/users_list.js";
import { register_users_update } from "./tools/users_update.js";
import { register_users_setActiveStatus } from "./tools/users_setActiveStatus.js";
import { register_roles_list } from "./tools/roles_list.js";
import { register_roles_create } from "./tools/roles_create.js";
import { register_roles_update } from "./tools/roles_update.js";
import { register_roles_addUserToRole } from "./tools/roles_addUserToRole.js";
import { register_roles_getUsersInRole } from "./tools/roles_getUsersInRole.js";
import { register_settings } from "./tools/settings.js";
import { register_settings__id } from "./tools/settings__id.js";
import { register_login } from "./tools/login.js";

async function main() {
  // Initialize the MCP server
  const server = new McpServer({
    name: "workspace-admin-mcp",
    version: "1.0.0",
  });

  // Set up Rocket.Chat client
  const rcUrl = process.env.RC_URL ?? "http://localhost:3000";
  const rcClient = new RCClient(rcUrl);

  // Authenticate with Rocket.Chat
  const username = process.env.RC_USER;
  const password = process.env.RC_PASSWORD;

  if (!username || !password) {
    console.error("Error: RC_USER and RC_PASSWORD environment variables are required.");
    process.exit(1);
  }

  await authenticate(rcClient, username, password);

  // Register tools
  register_statistics(server, rcClient);
  register_engagementdashboard_users_activeusers(server, rcClient);
  register_users_list(server, rcClient);
  register_users_update(server, rcClient);
  register_users_setActiveStatus(server, rcClient);
  register_roles_list(server, rcClient);
  register_roles_create(server, rcClient);
  register_roles_update(server, rcClient);
  register_roles_addUserToRole(server, rcClient);
  register_roles_getUsersInRole(server, rcClient);
  register_settings(server, rcClient);
  register_settings__id(server, rcClient);
  register_login(server, rcClient);

  // Connect via stdio transport
  const transport = new StdioServerTransport();
  await server.connect(transport);

  console.error(`workspace-admin-mcp MCP server running (13 tools)`);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
