/**
 * MCP Tool: chat_react
 * React to Message
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/chat.react
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const chat_reactSchema = z.object({
    messageId: z.string().describe("The message ID to react to."),
    emoji: z.string().optional().describe("The emoji to react with. It's required if you aren't using the `reaction` parameter."),
    reaction: z.string().optional().describe("The reaction to use. It's required if you aren't using the `emoji` parameter."),
    shouldReact: z.boolean().optional().describe("Boolean to specify if the reaction should be added or removed.")
  });

export function register_chat_react(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "chat_react",
    "React to Message",
    chat_reactSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/chat.react";
        const body = {
          messageId: params.messageId,
          emoji: params.emoji,
          reaction: params.reaction,
          shouldReact: params.shouldReact
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
