/**
 * MCP Tool: chat_postMessage
 * Post Message
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/chat.postMessage
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const chat_postMessageSchema = z.object({});

export function register_chat_postMessage(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "chat_postMessage",
    "Post Message",
    chat_postMessageSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/chat.postMessage";
        const result = await rcClient.post(apiPath, params);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
