/**
 * MCP Tool: chat_getThreadMessages
 * Get Thread Messages
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/chat.getThreadMessages
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const chat_getThreadMessagesSchema = z.object({
    offset: z.number().optional().describe("Number of items to \"skip\" in the query, i.e. requests return count items, skipping the first offset items. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    count: z.number().optional().describe("The number of items to return.  Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    sort: z.string().optional().describe("List of fields to order by, and in which direction. This is a JSON object, with properties listed in desired order, with values of 1 for ascending, or -1 for descending. For example, `{ \"value\": -1, \"_id\": 1 }`. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    query: z.string().optional().describe("This parameter allows you to use MongoDB query operators to search for specific data. For example, to query users with a name that contains the letter \"g\": query=`{ \"name\": { \"$regex\": \"g\" }}`. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#query-and-fields) to learn more."),
    fields: z.string().optional().describe("This parameter accepts a JSON object with properties that have a value of 1 or 0 to include or exclude them in the response. For example, to only retrieve the usernames of users: fields=`{ \"username\": 1 }`. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#query-and-fields) to learn more."),
    tmid: z.string().describe("The thread message ID.")
  });

export function register_chat_getThreadMessages(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "chat_getThreadMessages",
    "Get Thread Messages",
    chat_getThreadMessagesSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/chat.getThreadMessages";
        const queryParts: string[] = [];
        if (params.offset !== undefined) queryParts.push(`offset=${encodeURIComponent(String(params.offset))}`);
        if (params.count !== undefined) queryParts.push(`count=${encodeURIComponent(String(params.count))}`);
        if (params.sort !== undefined) queryParts.push(`sort=${encodeURIComponent(String(params.sort))}`);
        if (params.query !== undefined) queryParts.push(`query=${encodeURIComponent(String(params.query))}`);
        if (params.fields !== undefined) queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
        if (params.tmid !== undefined) queryParts.push(`tmid=${encodeURIComponent(String(params.tmid))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
