/**
 * MCP Tool: chat_pinMessage
 * Pin Message
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/chat.pinMessage
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const chat_pinMessageSchema = z.object({
    messageId: z.string().describe("The message ID that you want to pin.")
  });

export function register_chat_pinMessage(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "chat_pinMessage",
    "Pin Message",
    chat_pinMessageSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/chat.pinMessage";
        const body = {
          messageId: params.messageId
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
