/**
 * MCP Tool: chat_getPinnedMessages
 * Get Pinned Messages
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/chat.getPinnedMessages
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const chat_getPinnedMessagesSchema = z.object({
    roomId: z.string().describe("The room ID."),
    offset: z.number().optional().describe("Number of items to \"skip\" in the query, i.e. requests return count items, skipping the first offset items. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    count: z.number().optional().describe("The number of items to return.  Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    sort: z.string().optional().describe("List of fields to order by, and in which direction. This is a JSON object, with properties listed in desired order, with values of 1 for ascending, or -1 for descending. For example, `{ \"value\": -1, \"_id\": 1 }`. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more.")
  });

export function register_chat_getPinnedMessages(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "chat_getPinnedMessages",
    "Get Pinned Messages",
    chat_getPinnedMessagesSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/chat.getPinnedMessages";
        const queryParts: string[] = [];
        if (params.roomId !== undefined) queryParts.push(`roomId=${encodeURIComponent(String(params.roomId))}`);
        if (params.offset !== undefined) queryParts.push(`offset=${encodeURIComponent(String(params.offset))}`);
        if (params.count !== undefined) queryParts.push(`count=${encodeURIComponent(String(params.count))}`);
        if (params.sort !== undefined) queryParts.push(`sort=${encodeURIComponent(String(params.sort))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
