/**
 * MCP Tool: dm_create
 * Create DM
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/dm.create
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const dm_createSchema = z.object({});

export function register_dm_create(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "dm_create",
    "Create DM",
    dm_createSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/dm.create";
        const result = await rcClient.post(apiPath, params);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
