/**
 * MCP Tool: rooms_createDiscussion
 * Create Discussion
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/rooms.createDiscussion
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const rooms_createDiscussionSchema = z.object({
    prid: z.string().describe("Parent room ID of the discussion."),
    t_name: z.string().describe("Discussion name."),
    users: z.array(z.string()).optional().describe("Array of users to join in the discussion, if not provided, it will be an empty array. (Note: if provided, it must be an array)."),
    pmid: z.string().optional().describe("Parent message ID (if the discussion comes from a message)."),
    reply: z.string().optional().describe("The reply of the discussion.")
  });

export function register_rooms_createDiscussion(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "rooms_createDiscussion",
    "Create Discussion",
    rooms_createDiscussionSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/rooms.createDiscussion";
        const body = {
          prid: params.prid,
          t_name: params.t_name,
          users: params.users,
          pmid: params.pmid,
          reply: params.reply
        };
        const result = await rcClient.post(apiPath, body);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
