/**
 * MCP Tool: rooms_autocomplete_channelAndPrivate
 * Autocomplete Room Name for Private and Public Rooms
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/rooms.autocomplete.channelAndPrivate
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const rooms_autocomplete_channelAndPrivateSchema = z.object({
    selector: z.string().describe("The term to be completed. It only applies to room name.")
  });

export function register_rooms_autocomplete_channelAndPrivate(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "rooms_autocomplete_channelAndPrivate",
    "Autocomplete Room Name for Private and Public Rooms",
    rooms_autocomplete_channelAndPrivateSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/rooms.autocomplete.channelAndPrivate";
        const queryParts: string[] = [];
        if (params.selector !== undefined) queryParts.push(`selector=${encodeURIComponent(String(params.selector))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
