/**
 * MCP Tool: channels_list
 * Get Channel List
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: get /api/v1/channels.list
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const channels_listSchema = z.object({
    offset: z.number().optional().describe("Number of items to \"skip\" in the query, i.e. requests return count items, skipping the first offset items. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    count: z.number().optional().describe("The number of items to return. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#pagination) to learn more."),
    query: z.string().optional().describe("This parameter allows you to use MongoDB query operators to search for specific data. For example, to query users with a name that contains the letter \"g\": `query={ \"name\": { \"$regex\": \"g\" } }`. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#query-and-fields) to learn more."),
    fields: z.string().optional().describe("This parameter accepts a JSON object with properties that have a value of 1 or 0 to include or exclude them in the response. For example, to only retrieve the usernames of users: `fields={ \"username\": 1 }`. Refer to the [official documentation](https://developer.rocket.chat/apidocs/query-parameters#query-and-fields) to learn more."),
    sort: z.string().optional().describe("Sort the channels in ascending (`1`) or descending (`-1`) order. The value must be entered as a JSON object. The options are as follows:  * `name`: Sort by the channel name. For example, `sort={\"name\":1}` (this is the default sorting mechanism).  * `ts`: Sort by channel creation timestamp. For example, `sort={\"ts\":-1}`  * `usersCount`: Sort by the number of users in the channel. For example, `sort={\"usersCount\":1}`")
  });

export function register_channels_list(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "channels_list",
    "Get Channel List",
    channels_listSchema.shape,
    async (params) => {
      try {
        const apiPath = "/api/v1/channels.list";
        const queryParts: string[] = [];
        if (params.offset !== undefined) queryParts.push(`offset=${encodeURIComponent(String(params.offset))}`);
        if (params.count !== undefined) queryParts.push(`count=${encodeURIComponent(String(params.count))}`);
        if (params.query !== undefined) queryParts.push(`query=${encodeURIComponent(String(params.query))}`);
        if (params.fields !== undefined) queryParts.push(`fields=${encodeURIComponent(String(params.fields))}`);
        if (params.sort !== undefined) queryParts.push(`sort=${encodeURIComponent(String(params.sort))}`);
        const query = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const fullPath = `${apiPath}${query}`;
        const result = await rcClient.get(fullPath);
        return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Error: ${message}` }], isError: true };
      }
    }
  );
}
