/**
 * MCP Tool: set_status_and_notify
 * Set your status, resolve a channel by name, and post a status update message to it. Chains user-management + rooms + messaging.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/users.setStatus
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const set_status_and_notifySchema = z.object({
    statusText: z.string().optional().describe("Custom status message text"),
    status: z.string().optional().describe("Online status: online, away, busy, offline"),
    notifyChannel: z.string().describe("Channel name to post status update to"),
    notifyMessage: z.string().describe("Status update message to post in the channel")
  });

export function register_set_status_and_notify(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "set_status_and_notify",
    "Set your status, resolve a channel by name, and post a status update message to it. Chains user-management + rooms + messaging.",
    set_status_and_notifySchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed

        // Store results from each step for parameter wiring
        const stepResults: unknown[] = [];

        // ── Step 1: Set user status ──
        const step0Params: Record<string, unknown> = {};
        if (params.statusText !== undefined) step0Params["message"] = params.statusText;
        if (params.status !== undefined) step0Params["status"] = params.status;
        let step0Result;
        step0Result = await rcClient.post("/api/v1/users.setStatus", step0Params);
        stepResults.push(step0Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 2: Resolve notification channel by name ──
        const step1Params: Record<string, unknown> = {};
        if (params.notifyChannel !== undefined) step1Params["roomName"] = params.notifyChannel;
        let step1Result;
        {
          const step1Query = Object.entries(step1Params).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join("&");
          const step1Path = step1Query ? `/api/v1/rooms.info?${step1Query}` : "/api/v1/rooms.info";
          step1Result = await rcClient.get(step1Path);
        }
        stepResults.push(step1Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 3: Post status update message to the channel ──
        const step2Params: Record<string, unknown> = {};
        if (params.notifyMessage !== undefined) step2Params["text"] = params.notifyMessage;
        step2Params["roomId"] = (stepResults[1] as any)?.room?._id;
        let step2Result;
        step2Result = await rcClient.post("/api/v1/chat.postMessage", step2Params);
        stepResults.push(step2Result);

        // Return the final result from step 3
        return { content: [{ type: "text" as const, text: JSON.stringify(step2Result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Workflow "${"set_status_and_notify"}" failed: ${message}` }], isError: true };
      }
    }
  );
}
