/**
 * MCP Tool: setup_project_workspace
 * Create a project channel, set its description and topic, then post a welcome message. Chains 4 API calls into one platform operation.
 *
 * Auto-generated by rc-mcp — do not edit manually.
 * Endpoint: post /api/v1/channels.create
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { RCClient } from "../rc-client.js";

export const setup_project_workspaceSchema = z.object({
    channelName: z.string().describe("Name for the new project channel"),
    description: z.string().optional().describe("Project channel description"),
    topic: z.string().optional().describe("Project channel topic"),
    welcomeMessage: z.string().optional().describe("Welcome message to post in the new channel")
  });

export function register_setup_project_workspace(server: McpServer, rcClient: RCClient): void {
  server.tool(
    "setup_project_workspace",
    "Create a project channel, set its description and topic, then post a welcome message. Chains 4 API calls into one platform operation.",
    setup_project_workspaceSchema.shape,
    async (params) => {
      try {
        // Auth is pre-configured from .env — no per-call credentials needed

        // Store results from each step for parameter wiring
        const stepResults: unknown[] = [];

        // ── Step 1: Create the project channel ──
        const step0Params: Record<string, unknown> = {};
        if (params.channelName !== undefined) step0Params["name"] = params.channelName;
        let step0Result;
        step0Result = await rcClient.post("/api/v1/channels.create", step0Params);
        stepResults.push(step0Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 2: Set the channel description ──
        const step1Params: Record<string, unknown> = {};
        if (params.description !== undefined) step1Params["description"] = params.description;
        step1Params["roomId"] = (stepResults[0] as any)?.channel?._id;
        let step1Result;
        step1Result = await rcClient.post("/api/v1/channels.setDescription", step1Params);
        stepResults.push(step1Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 3: Set the channel topic ──
        const step2Params: Record<string, unknown> = {};
        if (params.topic !== undefined) step2Params["topic"] = params.topic;
        step2Params["roomId"] = (stepResults[0] as any)?.channel?._id;
        let step2Result;
        step2Result = await rcClient.post("/api/v1/channels.setTopic", step2Params);
        stepResults.push(step2Result);

        // Small delay to ensure previous operations are fully processed by the server
        await new Promise(resolve => setTimeout(resolve, 500));

        // ── Step 4: Post welcome message in the new channel ──
        const step3Params: Record<string, unknown> = {};
        if (params.welcomeMessage !== undefined) step3Params["text"] = params.welcomeMessage;
        step3Params["roomId"] = (stepResults[0] as any)?.channel?._id;
        let step3Result;
        step3Result = await rcClient.post("/api/v1/chat.postMessage", step3Params);
        stepResults.push(step3Result);

        // Return the final result from step 4
        return { content: [{ type: "text" as const, text: JSON.stringify(step3Result, null, 2) }] };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return { content: [{ type: "text" as const, text: `Workflow "${"setup_project_workspace"}" failed: ${message}` }], isError: true };
      }
    }
  );
}
